# Generated by Django 5.0.6 on 2024-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('po_box', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_phone_number', models.CharField(max_length=15)),
                ('passport_number', models.CharField(max_length=50)),
                ('visa_document', models.FileField(blank=True, null=True, upload_to='visas/')),
                ('departure_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
            ],
        ),
    ]
